import {
  ChakraProvider,
} from "@chakra-ui/react";
import "./global.css";
import {ReactNode} from "react";

export const metadata = {
  title: "Nutrillo Dashboard",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="es">
      <body>
        <ChakraProvider>{children}</ChakraProvider>
      </body>
    </html>
  );
}
