import "./global.css";
import { ReactNode } from "react";
import { ClientProviders } from "./providers";

export const metadata = {
  title: "Nutrillo Dashboard",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="es">
      <body>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
